// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vztmwwfbhxlzyantrnmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6dG13d2ZiaHhsenlhbnRybm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NDc1NTMsImV4cCI6MjEwMjIyMzU1M30.1sV3OUV1DWlH9ha8UHg5yvocNpiDFAhiBaRF9ky01RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Sequential in-memory lock: replaces the Web Locks API (which deadlocks on
// Firefox iOS / some Android WebViews). A promise chain serialises all auth
// operations so concurrent token-refresh calls can't revoke each other's tokens.
// The catch resets the chain on failure so a single network error doesn't
// silently block all subsequent auth operations forever.
let _authLock: Promise<unknown> = Promise.resolve();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    lock: (_name, _acquireTimeout, fn) => {
      const result = _authLock.then(() => fn());
      _authLock = result.catch(() => undefined);
      return result;
    },
  }
});